# Generated by Django 5.0.4 on 2024-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rindus_assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
